default_stages: [commit]
repos:
  - hooks:
      - id: commitizen
        stages: [commit-msg]
    repo: https://github.com/commitizen-tools/commitizen
    rev: master
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: master
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: stable
  - hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
    repo: https://github.com/pycqa/flake8
    rev: master
  - hooks:
      - id: pylint
    repo: https://github.com/pycqa/pylint
    rev: master
